### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by PXY0411** [CSSLab/maia-chess#58]
When I try to run the commend  python3 train_maia.py maia_config.yaml,here is part of the error message.
Process Process-19:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/pxy/maia/move_prediction/maia_chess_backend/maia/chunkparser.py", line 256, in task
    writer.send_bytes(item)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Did somebody have the same problem?

**Comment by reidmcy** [comment]
How many workers do you have? That looks like the receiving process died, there was likely another error message about that before this one

**Comment by PXY0411** [comment]
> How many workers do you have? That looks like the receiving process died, there was likely another error message about that before this one

2023-07-27 10:21:58 Using 14 worker processes.
Here might be another error message.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Using 1 evaluation batches
2023-07-27 15:22:28.437999: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:543] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
Searched for CUDA in the following directories:
  ./cuda_sdk_lib
  /usr/local/cuda-11.8
  /usr/local/cuda
  .
You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.

**Comment by reidmcy** [comment]
Looks like the main process can't find CUDA. You should fix your CUDA install before trying to do training. You can use the TF device listing systems to check if it's working without running the whole script.

**Comment by reidmcy** [comment]
What is the actual error message from the main process? What you provided was a CUDA issue

**Comment by PXY0411** [comment]
> 来自主进程的实际错误消息是什么？您提供的是 CUDA 问题
The actual error message is 'BrokenPipeError: [Errno 32] Broken pipe'

**Comment by reidmcy** [comment]
That's not the main process and is incomplete. What is the complete stderr output of the main process?

**Comment by PXY0411** [comment]
> That's not the main process and is incomplete. What is the complete stderr output of the main process?

This is error log of the whole process[error.log](https://github.com/CSSLab/maia-chess/files/12186212/error.log)

**Comment by reidmcy** [comment]
I don't see the previous error "`Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. `". That looks to only be from the worker processes not the main process. I can't help you if you don't provide the relevant information
